/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exam1;

import java.io.*;
import java.util.*;
import javax.swing.JComboBox;

/**
 *
 * @author bmetzelaar16
 */
public class UnderOver extends javax.swing.JFrame {
    List<String> storedUsers = new ArrayList<String>();
    int choice = 0; // combobox choice
    Double userMoney = 0.0;


    public void readFile(List<String> storedUsers) {
        // List<String> users = new ArrayList<String>();
        File f = new File("Z:\\GitHub\\CS372\\Exams\\Exam1\\src\\exam1\\users.txt");
        try {
            BufferedReader rdr = new BufferedReader(new FileReader(f));
            String line;
            while ((line = rdr.readLine()) != null) {
                System.out.println(line);
                storedUsers.add(line);
            }
            rdr.close();
            
            // do something with the list of users
        } catch (Exception ex) {
            System.out.print("ERROR:");
            System.out.println(ex.getMessage());
        }

    }

    public void writeFile() {

    }
    
    /**
     * Creates new form UnderOver
     */
    public UnderOver() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfLogin = new javax.swing.JTextField();
        btnLogin = new javax.swing.JToggleButton();
        lbWelcome = new javax.swing.JLabel();
        lbMoney = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfUnder7 = new javax.swing.JTextField();
        tfOver7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lbResults = new javax.swing.JLabel();
        lbDiceRoll1 = new javax.swing.JLabel();
        lbDiceRoll2 = new javax.swing.JLabel();
        lbRollPayout = new javax.swing.JLabel();
        tfExactly7 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        tfBet = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Login");

        jLabel2.setText("Username");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lbWelcome.setText("Welcome");
        lbWelcome.setToolTipText("");

        lbMoney.setText("Money: $0.00");

        jLabel6.setText("Place Bet");

        jLabel7.setText("Under 7");

        jLabel8.setText("Over 7");

        jLabel9.setText("Exactly 7");

        jButton1.setText("Role Dice");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbResults.setText("Results");

        lbDiceRoll1.setText("Dice 1: 0");

        lbDiceRoll2.setText("Dice 2: 0");

        lbRollPayout.setText("$0.00");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Under 7", "Over 7", "Exactly 7" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbDiceRoll1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbResults)
                        .addGap(84, 84, 84))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfUnder7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfBet, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                            .addComponent(tfOver7, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(63, 63, 63)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfExactly7)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbWelcome)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbMoney)
                                    .addComponent(btnLogin)))
                            .addComponent(jButton1))
                        .addGap(96, 96, 96))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbDiceRoll2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbRollPayout)
                        .addGap(87, 87, 87))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbWelcome)
                    .addComponent(lbMoney))
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUnder7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfOver7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfExactly7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbResults)
                    .addComponent(lbDiceRoll1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDiceRoll2)
                    .addComponent(lbRollPayout))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // LOGIN BUTTON
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // LOGIN BUTTON CLICKED
        // tfLogin
        String user = this.tfLogin.getText();   // Get username from login box
        
        readFile(storedUsers);  // get all user's that are currently saved
        if (storedUsers.contains(user) == true){
            
        } else {
            writeFile();
        }
        
        
        System.out.println(storedUsers.size());
        
        lbWelcome.setText("Welcome " + user);    // Set welcome message
        // TODO set user money
        String displayMoney = String.format("Money: $%.2f", userMoney);
        lbMoney.setText(displayMoney);
    }//GEN-LAST:event_btnLoginActionPerformed

    // ROLL THE DICE BUTTON
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Double userBet = Double.parseDouble(tfBet.getText());;
        
        Dice d1 = new Dice(6);
        Dice d2 = new Dice(6);

        int roll1 = d1.roll();
        int roll2 = d2.roll();
        int result = roll1 + roll2; // overall result of the two dice
        
        double rollPayout = 0.0;
        
        if (choice == 1){
            if (result > 6){ // lost
                userMoney -= userBet;
                userBet *= -1;
            } else { // won
                userMoney += userBet;
            }
        }
        if (choice == 2){
            if (result < 8){ // lost
                userMoney -= userBet;
                userBet *= -1;
            } else { // won
                userMoney += userBet;
            }
        }
        if (choice == 3){
            if (result != 7){ // lost
                userMoney -= userBet;
                userBet *= -1;
            } else { // won
                userMoney += (userBet * 4);
                userBet *= 4;
            }
        }
        
        String d1Text = String.format("Dice 1: %d", roll1);
        lbDiceRoll1.setText(d1Text);
        
        String d2Text = String.format("Dice 2: %d", roll2);
        lbDiceRoll2.setText(d2Text);
        
        String displayMoney = String.format("$%.2f", userMoney);
        lbMoney.setText(displayMoney);
        
        String disRollPayout = String.format("$%.2f", userBet);
        lbRollPayout.setText(disRollPayout);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        //JComboBox cb = (JComboBox)e.getSource();
        JComboBox cb = (JComboBox)evt.getSource();
        String comboChoice = (String)cb.getSelectedItem();

        
        //comboChoice.compareTo("Under 7");
        if (comboChoice == "Under 7"){
            choice = 1;
        } else if (comboChoice == "Over 7"){
            choice = 2;
        } else if (comboChoice == "Exactly 7"){
            choice = 3;
        } else {
            choice = 0;
        }
            
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnderOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnderOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnderOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnderOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnderOver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbDiceRoll1;
    private javax.swing.JLabel lbDiceRoll2;
    private javax.swing.JLabel lbMoney;
    private javax.swing.JLabel lbResults;
    private javax.swing.JLabel lbRollPayout;
    private javax.swing.JLabel lbWelcome;
    private javax.swing.JTextField tfBet;
    private javax.swing.JTextField tfExactly7;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JTextField tfOver7;
    private javax.swing.JTextField tfUnder7;
    // End of variables declaration//GEN-END:variables
}
