/*
 * HW02-PR2_6: Homework Tracker
 * By: Brennan Metzelaar
 * Edited: 1/9/2015
 * Due: 1/9/2015
 */
package pr2_6;

import java.util.*;

/**
 *
 * @author Brennan
 */
public class HomeworkTracker extends javax.swing.JFrame {

    List grades = new ArrayList();
    ValueRange vr = new ValueRange();

    /**
     * Creates new form HomeworkTracker
     */
    public HomeworkTracker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbtAssignments = new javax.swing.JLabel();
        lbtEnterScore = new javax.swing.JLabel();
        lbCurrAssignment = new javax.swing.JLabel();
        tfScore = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lbtHWGrades = new javax.swing.JLabel();
        lbtBest = new javax.swing.JLabel();
        lbtWorst = new javax.swing.JLabel();
        lbtAverage = new javax.swing.JLabel();
        lbBest = new javax.swing.JLabel();
        lbWorst = new javax.swing.JLabel();
        lbAverage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbtAssignments.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbtAssignments.setText("Assignments");

        lbtEnterScore.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbtEnterScore.setText("Enter Score");

        lbCurrAssignment.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lbCurrAssignment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbCurrAssignment.setText("jLabel3");

        tfScore.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lbtHWGrades.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbtHWGrades.setText("Homework Grades");

        lbtBest.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbtBest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbtBest.setText("Best");

        lbtWorst.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbtWorst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbtWorst.setText("Worst");

        lbtAverage.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbtAverage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbtAverage.setText("Average");

        lbBest.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbBest.setText("----");

        lbWorst.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbWorst.setText("----");

        lbAverage.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbAverage.setText("----");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbtAssignments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbCurrAssignment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbtEnterScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfScore))
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbtAverage)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbtWorst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbtBest, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbBest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbAverage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbWorst, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnSubmit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(lbtHWGrades)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtAssignments)
                    .addComponent(lbtEnterScore))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCurrAssignment))
                .addGap(28, 28, 28)
                .addComponent(btnSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(lbtHWGrades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtAverage)
                    .addComponent(lbAverage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtBest)
                    .addComponent(lbBest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtWorst)
                    .addComponent(lbWorst))
                .addGap(77, 77, 77))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param evt 
     */
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // When button is clicked add HW assignment and value into a map for storage
        double c = Double.parseDouble(this.tfScore.getText());
        this.tfScore.setText("");
        grades.add(c);

        // Average Grade Display
        String f = String.format("%1.2f", vr.getAverage(grades));
        lbAverage.setText(f);

        // Best Grade
        f = String.format("%1.2f", vr.getMax(grades));
        lbBest.setText(f);

        // Worst Grade
        f = String.format("%1.2f", vr.getMin(grades));
        lbWorst.setText(f);
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeworkTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeworkTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeworkTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeworkTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeworkTracker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lbAverage;
    private javax.swing.JLabel lbBest;
    private javax.swing.JLabel lbCurrAssignment;
    private javax.swing.JLabel lbWorst;
    private javax.swing.JLabel lbtAssignments;
    private javax.swing.JLabel lbtAverage;
    private javax.swing.JLabel lbtBest;
    private javax.swing.JLabel lbtEnterScore;
    private javax.swing.JLabel lbtHWGrades;
    private javax.swing.JLabel lbtWorst;
    private javax.swing.JTextField tfScore;
    // End of variables declaration//GEN-END:variables
}
